import { spawn } from "node:child_process";
import { simpleGit as createSimpleGit } from "simple-git";
import type { ValidationResult } from "../validate/types.js";
import type { PatchResult } from "../patch/types.js";
import type { CommitConfig, CommitOutcome } from "./types.js";

export * from "./types.js";

function slugify(text: string, maxLen = 40): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, maxLen);
}

/** Run `git apply` with the diff piped to stdin. */
function runGitApply(repoRoot: string, args: string[], diff: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn("git", ["apply", ...args, "-"], { cwd: repoRoot });
    let stderr = "";
    child.stderr.on("data", (d: Buffer) => { stderr += d.toString(); });
    child.on("close", (code) => {
      if (code === 0) resolve();
      else reject(new Error(`git apply failed (exit ${code}): ${stderr}`));
    });
    child.stdin.write(diff);
    child.stdin.end();
  });
}

async function applyDiff(repoRoot: string, diff: string): Promise<void> {
  if (!diff.trim()) return;
  await runGitApply(repoRoot, ["--index"], diff);
}

async function revertDiff(repoRoot: string, diff: string): Promise<void> {
  if (!diff.trim()) return;
  await runGitApply(repoRoot, ["--index", "--reverse"], diff);
}

async function createGitHubPR(
  repo: string,
  token: string,
  head: string,
  base: string,
  title: string,
  body: string,
  draft: boolean,
  label: string
): Promise<string> {
  const [owner, repoName] = repo.split("/") as [string, string];

  const res = await fetch(`https://api.github.com/repos/${owner}/${repoName}/pulls`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
      "X-GitHub-Api-Version": "2022-11-28",
    },
    body: JSON.stringify({ title, body, head, base, draft }),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`GitHub PR creation failed (${res.status}): ${err}`);
  }

  const pr = (await res.json()) as { html_url: string; number: number };

  // Attach label (best-effort — don't fail the pipeline if this errors)
  try {
    const [o, r] = repo.split("/") as [string, string];
    await fetch(
      `https://api.github.com/repos/${o}/${r}/issues/${pr.number}/labels`,
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: "application/vnd.github+json",
          "Content-Type": "application/json",
          "X-GitHub-Api-Version": "2022-11-28",
        },
        body: JSON.stringify({ labels: [label] }),
      }
    );
  } catch {
    // ignore label errors
  }

  return pr.html_url;
}

/**
 * Commit + PR stage.
 *
 * Workflow:
 * 1. Create a new branch off `baseBranch`.
 * 2. Apply the unified diff via `git apply`.
 * 3. Call the `validate` callback (ValidationLayer.validate).
 * 4a. If validation passes → commit, push, open PR → return CommitResult.
 * 4b. If validation fails → revert + return to baseBranch → return RevertResult.
 */
export class CommitAndPR {
  private readonly git: ReturnType<typeof createSimpleGit>;
  private readonly repoRoot: string;
  private readonly config: Required<CommitConfig>;

  constructor(repoRoot: string, config: CommitConfig) {
    this.repoRoot = repoRoot;
    this.git = createSimpleGit(repoRoot);
    this.config = {
      baseBranch: config.baseBranch ?? "main",
      branchPrefix: config.branchPrefix ?? "selfix",
      githubToken: config.githubToken,
      githubRepo: config.githubRepo,
      prLabel: config.prLabel ?? "selfix",
      draftPr: config.draftPr ?? false,
    };
  }

  async run(
    patch: PatchResult,
    validate: (patch: PatchResult) => Promise<ValidationResult>
  ): Promise<CommitOutcome> {
    if (!patch.diff.trim()) {
      const noopValidation: ValidationResult = {
        patch,
        score: 1,
        baselineScore: 1,
        passed: true,
        summary: "No diff to apply.",
      };
      return { success: false, reason: "Empty diff — nothing to commit.", validation: noopValidation };
    }

    const branchSlug = slugify(patch.diagnosis.explanation);
    const branch = `${this.config.branchPrefix}/${branchSlug}`;

    // Ensure we start from baseBranch
    await this.git.checkout(this.config.baseBranch);
    await this.git.checkoutLocalBranch(branch);

    let validation: ValidationResult;
    try {
      await applyDiff(this.repoRoot, patch.diff);

      await this.git.add("-A");
      await this.git.commit(
        `fix: ${patch.diagnosis.explanation.slice(0, 72)}\n\nGenerated by selfix.\nCategory: ${patch.diagnosis.category}\nSeverity: ${patch.diagnosis.severity}\n\n${patch.rationale}`
      );

      validation = await validate(patch);
    } catch (err) {
      // Patch application or git operation failed — clean up
      try {
        await this.git.checkout(this.config.baseBranch);
        await this.git.deleteLocalBranch(branch, true);
      } catch {
        // best-effort cleanup
      }
      return {
        success: false,
        reason: `Patch application failed: ${String(err)}`,
        validation: {
          patch,
          score: 0,
          baselineScore: 0,
          passed: false,
          summary: String(err),
        },
      };
    }

    if (!validation.passed) {
      // Revert: go back to base, delete temp branch
      try {
        await this.git.checkout(this.config.baseBranch);
        await this.git.deleteLocalBranch(branch, true);
      } catch {
        // best-effort cleanup
      }
      return {
        success: false,
        reason: `Validation failed (score ${validation.score.toFixed(2)} < baseline ${validation.baselineScore.toFixed(2)})`,
        validation,
      };
    }

    // Push and open PR
    const remote = "origin";
    await this.git.push(remote, branch, ["--set-upstream"]);

    const prTitle = `fix: ${patch.diagnosis.explanation.slice(0, 72)}`;
    const prBody = [
      `## selfix automated fix`,
      ``,
      `**Category:** \`${patch.diagnosis.category}\``,
      `**Severity:** \`${patch.diagnosis.severity}\``,
      ``,
      `### Root cause`,
      patch.diagnosis.explanation,
      ``,
      `### Proposed change`,
      patch.rationale,
      ``,
      `### Validation`,
      `Score: ${validation.score.toFixed(2)} (baseline: ${validation.baselineScore.toFixed(2)})`,
      validation.summary,
      ``,
      `---`,
      `*Opened automatically by [selfix](https://github.com/your-org/selfix)*`,
    ].join("\n");

    const prUrl = await createGitHubPR(
      this.config.githubRepo,
      this.config.githubToken,
      branch,
      this.config.baseBranch,
      prTitle,
      prBody,
      this.config.draftPr,
      this.config.prLabel
    );

    return { success: true, branch, prUrl, validation };
  }
}
